<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,6,1,'5Li76aKY5ri4');
$cfg_Cs[3]=array(1,6,1,'5ama5ouN');
$cfg_Cs[15]=array(1,6,1,'5Lqy5a2Q');
$cfg_Cs[16]=array(1,6,1,'5L2T6IKy');
$cfg_Cs[6]=array(0,1,1,'54Ot6Zeo6LWE6K6v');
$cfg_Cs[8]=array(0,1,1,'5Liq5Lq65Lit5b+D');
$cfg_Cs[9]=array(0,-8,1,'55uu55qE5Zyw');
$cfg_Cs[13]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[17]=array(1,6,1,'5oi35aSW');
$cfg_Cs[12]=array(0,6,1,'5rS75Yqo');
$cfg_Cs[18]=array(1,6,1,'5rW35bKb');
?>