<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,2,1,'5Li76aKY5ri4');
$cfg_Cs[3]=array(1,6,1,'5Zu95aSW');
$cfg_Cs[4]=array(1,6,1,'5Zu95YaF');
$cfg_Cs[5]=array(1,6,1,'54Gr5pif');
$cfg_Cs[6]=array(0,1,1,'54Ot6Zeo6LWE6K6v');
$cfg_Cs[8]=array(0,1,1,'5Liq5Lq65Lit5b+D');
$cfg_Cs[9]=array(0,-8,1,'55uu55qE5Zyw');
$cfg_Cs[13]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[12]=array(0,6,1,'5rS75Yqo');
?>