<?php
$z[0]=Array("field","",48,76);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",78,107);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",148,176);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n           <li><a href=\"[field:arcurl/]\" title=\"[field:title function='html2text(@me)' /]\"><img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\"/></a></li>\r\n		",256,488);
$z[3][4]=array();
$z[3][4]['row']="3";
$z[3][4]['type']="image.";
$z[4]=Array("arclist","\r\n            <li><span class=\"date\">[field:pubdate function=\"GetDateMK(@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n			",549,742);
$z[4][4]=array();
$z[4][4]['titlelen']="60";
$z[4][4]['row']="5";

?>