<?php
$z[0]=Array("include","",0,41);
$z[0][4]=array();
$z[0][4]['filename']="travel_top.htm";
$z[1]=Array("include","",83,127);
$z[1][4]=array();
$z[1][4]['filename']="travel_header.htm";
$z[2]=Array("include","",1449,1490);
$z[2][4]=array();
$z[2][4]['filename']="travel_nav.htm";
$z[3]=Array("arclist","\r\n						<div class=\"swiper-slide\">\r\n							<a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" />\r\n								<div class=\"recswipertext\">\r\n									<p class=\"name\">[field:title/]</p>\r\n									<div class=\"remark\">\r\n										<p>[field:description/]</p>\r\n									</div>\r\n								</div>\r\n							</a>\r\n						</div>\r\n						",5505,5888);
$z[3][4]=array();
$z[3][4]['flag']="p";
$z[3][4]['row']="6";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("include","",21612,21656);
$z[4][4]=array();
$z[4][4]['filename']="travel_bottom.htm";

?>