<?php
$z[0]=Array("include","",0,41);
$z[0][4]=array();
$z[0][4]['filename']="travel_top.htm";
$z[1]=Array("include","",83,127);
$z[1][4]=array();
$z[1][4]['filename']="travel_header.htm";
$z[2]=Array("loop","\r\n                        <div class=\"swiper-slide\"> <img src=\"[field:url/]\" /> </div>\r\n					",317,488);
$z[2][4]=array();
$z[2][4]['table']="tvl_uploads";
$z[2][4]['sort']="";
$z[2][4]['row']="4";
$z[2][4]['if']="mediatype = 1";
$z[3]=Array("include","",701,742);
$z[3][4]=array();
$z[3][4]['filename']="travel_nav.htm";
$z[4]=Array("arclist","\r\n						<div class=\"swiper-slide\">\r\n							<a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" />\r\n								<div class=\"recswipertext\">\r\n									<p class=\"name\">[field:title/]</p>\r\n									<div class=\"remark\">\r\n										<p>[field:description/]</p>\r\n									</div>\r\n								</div>\r\n							</a>\r\n						</div>\r\n						",4463,4846);
$z[4][4]=array();
$z[4][4]['flag']="h";
$z[4][4]['row']="6";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("sql","",5540,5630);
$z[5][4]=array();
$z[5][4]['sql']="<select name=";
$z[5][4]['select * from tvl_anchor;" id']="";
$z[5][4]['></select>']="";
$z[6]=Array("include","",20741,20785);
$z[6][4]=array();
$z[6][4]['filename']="travel_bottom.htm";

?>