<?php
$z[0]=Array("global","",705,730);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","\n                <li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\n                ",783,1043);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<li class='active'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>